/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.adito.relativedateexpression;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RelativeDateExpressionTest {
    @Test void testSomeLibraryMethod() {
        RelativeDateExpression classUnderTest = new RelativeDateExpression();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
